services:
  django:
    container_name: twitter-clone-django
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/code
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: twitter-clone-postgres
    image: postgres:16
    volumes:
      - ./db:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file:
      - ./backend/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db:
